receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "mysql-monitoring"
          scrape_interval: 5s
          static_configs:
            - targets: [ "mysqld-exporter:9104" ]
              labels:
                host_name: showcase
processors:
  batch:

exporters:
  otlp:
    endpoint: "skywalking-oap:11800" # The OAP Server address
    # The config format of OTEL version prior to 0.34.0, eg. 0.29.0, should be:
    # insecure: true
    tls:
      insecure: true
    #insecure: true
  # Exports data to the console
#  logging:
#    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [ prometheus ]
      processors: [ batch ]
      exporters: [ otlp ]